name: ${pom.name}
main: com.seiken.interest.Interest
version: ${pom.version}
description: >
             Mark locations on the map with custom names.
commands:
  mark:
    description: "Mark the current place. Use r: to specify a maximum radius. Use x: y: z: to specify a maximum on each axis."
    usage: |
           /<command> [r:## | x:## y:## z:##] place
           Example: /<command> place
           Example: /<command> r:5 place
           Example: /<command> x:4 y:6 z:7 place
  unmark:
    description: Unmark the current place
    usage: |
           /<command>
           Example: /<command>
  nearest:
    description: Find out the nearest mark
    usage: |
           /<command>
           Example: /<command>
  who:
    aliases: [where]
    description: Find out where people are
    usage: |
           /<command> [player]
           Example: /<command> Dutchy_